### ISSUE TITLE
Support for Script Injection Points

### ISSUE THREAD

**Issue by SandiyosDev** [mirus-ua/hugo-theme-re-terminal#17]
I'm using the re-terminal theme as a Hugo submodule in my project and would like to inject custom scripts (e.g., GoatCounter) into the <head> section of every page. 

Could you consider adding a native injection point in the re-terminal theme that allows users to easily insert custom scripts into the <head> section across all pages? This would be a helpful feature for users who want to extend the theme's functionality without directly modifying the theme files, especially when using it as a submodule.

**Comment by mirus-ua** [comment]
Hello. Have you tried to use [extended_head](https://github.com/mirus-ua/hugo-theme-re-terminal/blob/main/layouts/partials/extended_head.html)? 

You should put it in your project folder `<your blog>/layouts/partials/extended_head.html`, and your custom scripts, style tags, etc will be merged with the rest of the head tag
