### ISSUE TITLE
Images on post summaries don't show

### ISSUE THREAD

**Issue by gentleadam** [mirus-ua/hugo-theme-re-terminal#18]
![image](https://github.com/user-attachments/assets/69a62c62-95f9-49f5-a515-0e9062575d9d)

I have posts with images embedded using a directory in `static/posts/<postname>`. These appear fine on the individual posts, but do not render on the summary for the post in the homepage.

**Comment by mirus-ua** [comment]
Could you provide a code snippet of how you embed the image?

**Comment by gentleadam** [comment]
Yeah sure, 

I am just using markdown as below,
```
![Standard link](standardlink.png)
![Legacy pricing page](legacypricingpage.png)
```

I then have these images saved in a directory which has the same name as the post eg.

`thedevopsquest/static/posts/appservicepricingupdate`

**Comment by mirus-ua** [comment]
Use the static folder for this approach, like in demo site here `re-terminal/demoSite/static/img/css-variables-update.webp`

And if you use the path relative to the `static` folder in your MD files, like this `![img](/img/css-variables-update.webp)`, 
you will achieve good result for both pages

**Comment by gentleadam** [comment]
> Use the static folder for this approach, like in demo site here `re-terminal/demoSite/static/img/css-variables-update.webp`
> 
> And if you use the path relative to the `static` folder in your MD files, like this `![img](/img/css-variables-update.webp)`, you will achieve good result for both pages

Cool thanks, I'll try it out
