### ISSUE TITLE
Copyright footer is not centered

### ISSUE THREAD

**Issue by gentleadam** [mirus-ua/hugo-theme-re-terminal#19]
![image](https://github.com/user-attachments/assets/f3b126da-2f81-415f-b7ed-aacaf398990e)

When using the full screen the footer at the bottom of the page is not centered.

By the way, I am new here, I am happy to work on issues if you want me to 🙂

**Comment by mirus-ua** [comment]
Sure, open PR if you wish, or I do when have some spare time

**Comment by mirus-ua** [comment]
Hey @gentleadam 
I can't reproduce it. Did you make any changes to CSS in your codebase? Can you give some steps to reproduce or push the code to a public repo?

**Comment by mirus-ua** [comment]
@gentleadam please take a look at https://github.com/mirus-ua/hugo-theme-re-terminal/pull/30

**Comment by gentleadam** [comment]
Looks good to me!
