### ISSUE TITLE
links are not colored

### ISSUE THREAD

**Issue by cibersheep** [mirus-ua/hugo-theme-re-terminal#21]
I don't know if this is on purpose, but links are shown as white text and not accent color.

https://github.com/mirus-ua/hugo-theme-re-terminal/blob/fab58b1697f22639672dc1756b42707a8134c844/assets/css/main.scss#L60

If `a` is changed from `inherit` to `var(--accent)` this is "fixed"

**Comment by mirus-ua** [comment]
Hello. Thanks, you raised the topic.
The suggested changes affect all links, including buttons and menus, so they will definitely break backward compatibility without making a version bump.

Are you interested in a different color for links inside articles? I'm asking because better understating may helps to find out a solution

**Comment by cibersheep** [comment]
Thank you for your work.
I was thinking in coloring all links but definitively didn't thought about buttons.
I was looking for something like this in my website: https://amannolem.cat/relats/  but as you can see I use quite little elements.

I don't know what is your ideal for the theme. I can always add some personal css into my website, you know :)

**Comment by mirus-ua** [comment]
I see what you are trying to achieve. Maybe it's a good idea to add an optional CSS variable `--link-color` to the scope of the article layout because, indeed, some people prefer to highlight links with some color. These changes won't help you to colorize menu items, though...

**Comment by cibersheep** [comment]
That sounds really nice!

**Comment by mirus-ua** [comment]
> That sounds really nice!

Would you like to contribute? Or I can do it when I have some time. Just asking to prevent double work

**Comment by cibersheep** [comment]
I think you can go on this one. I'm not that good with sass, but I'll learn

**Comment by mirus-ua** [comment]
https://github.com/mirus-ua/hugo-theme-re-terminal/pull/25 was merged 

Use `--article-link-color: var(inherit); /* for you, who want to colorize your article links */` in your `static/style.css` to colorize article links
