### ISSUE TITLE
paginate is deprecated

### ISSUE THREAD

**Issue by cibersheep** [mirus-ua/hugo-theme-re-terminal#24]
I got a message with the latest HUGO that said `paginate = 5` is deprecated.

**Comment by mirus-ua** [comment]
A good catch, thank you.
For some reason, not Hugo 0.129 nor 0.138 didn't show me this warning message

**Comment by mirus-ua** [comment]
fixed here https://github.com/mirus-ua/hugo-theme-re-terminal/pull/22
